[package]
name = "rust_io_template"
version = "0.1.1"
edition = "2021"
description = "A simple Rust I/O template"
license = "MIT"
repository = "https://github.com/lduranovic/rust-io-template"

[lib]
path = "src/lib.rs"

[dependencies]
